name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build_win_ac24:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python Tools/download_and_unzip.py ${{ secrets.WIN_DEVKIT_AC24 }} Build
    - name: Generate Project
      run: cmake -B Build/AC24 -G "Visual Studio 16 2019" -A "x64" -T "v142" -DAC_API_DEVKIT_DIR="Build/API Development Kit 24.3000" .
    - name: Build Debug
      run: cmake --build Build/AC24 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build Build/AC24 --config RelWithDebInfo
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Dotbim Add-On AC24 Win
        path: Build/AC24/RelWithDebInfo/Dotbim_AC24_Win.apx
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: Build/AC24/RelWithDebInfo/Dotbim_AC24_Win.apx
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}

  build_win_ac25:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python Tools/download_and_unzip.py ${{ secrets.WIN_DEVKIT_AC25 }} Build
    - name: Generate Project
      run: cmake -B Build/AC25 -G "Visual Studio 16 2019" -A "x64" -T "v142" -DAC_API_DEVKIT_DIR="Build/API Development Kit 25.3000" .
    - name: Build Debug
      run: cmake --build Build/AC25 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build Build/AC25 --config RelWithDebInfo
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Dotbim Add-On AC25 Win
        path: Build/AC25/RelWithDebInfo/Dotbim_AC25_Win.apx
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: Build/AC25/RelWithDebInfo/Dotbim_AC25_Win.apx
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}

  build_win_ac26:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python Tools/download_and_unzip.py ${{ secrets.WIN_DEVKIT_AC26 }} Build
    - name: Generate Project
      run: cmake -B Build/AC26 -G "Visual Studio 16 2019" -A "x64" -T "v142" -DAC_API_DEVKIT_DIR="Build/API Development Kit 26.3000" .
    - name: Build Debug
      run: cmake --build Build/AC26 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build Build/AC26 --config RelWithDebInfo
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Dotbim Add-On AC26 Win
        path: Build/AC26/RelWithDebInfo/Dotbim_AC26_Win.apx
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: Build/AC26/RelWithDebInfo/Dotbim_AC26_Win.apx
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
