name: Build

on:
  workflow_dispatch:
  push:
    branches:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os-type }}

    strategy:
      matrix:
        os-type: [ windows-2019, macos-12 ]
        ac-version: [ 25, 26, 27 ]

    steps:
      - uses: actions/checkout@v3

      - name: Checkout the submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Run build script
        run: |
          python Tools/BuildAddOn.py --configFile config.json --acVersion ${{ matrix.ac-version }} --release --package

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
            artifacts: Build/Package/*.zip
            draft: true
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}
