name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build_win:
    strategy:
      matrix:
        params:
          - acVersion: 24
            devKitUrl: WIN_DEVKIT_AC24
            devKitDir: API Development Kit 24.3009
            platformToolset: v141
          - acVersion: 25
            devKitUrl: WIN_DEVKIT_AC25
            devKitDir: API Development Kit 25.3002
            platformToolset: v142
          - acVersion: 26
            devKitUrl: WIN_DEVKIT_AC26
            devKitDir: API Development Kit 26.3000  
            platformToolset: v142
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python Tools/download_and_unzip.py ${{ secrets[matrix.params.devKitUrl] }} Build
    - name: Generate Project
      run: cmake -B Build -G "Visual Studio 16 2019" -A "x64" -T "${{ matrix.params.platformToolset }}" -DAC_API_DEVKIT_DIR="Build/${{ matrix.params.devKitDir }}/Support" .
    - name: Build Debug
      run: cmake --build Build --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build Build --config RelWithDebInfo
    - name: Finalize file name
      run: copy Build/RelWithDebInfo/DotbimAddOn.apx Build/RelWithDebInfo/Dotbim_AC${{ matrix.params.acVersion }}_Win.apx
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Dotbim Add-On AC${{ matrix.params.acVersion }} Win
        path: Build/RelWithDebInfo/Dotbim_AC${{ matrix.params.acVersion }}_Win.apx
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: Build/RelWithDebInfo/Dotbim_AC${{ matrix.params.acVersion }}_Win.apx
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
